import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import {  } from 'lucide-react'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#0f172a' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 3, borderBottomColor: '#10b981', paddingBottom: 12, marginBottom: 20 },
  brand: { fontSize: 22, fontWeight: 'bold', color: '#10b981' },
  subtitle: { fontSize: 9, color: '#64748b' },
  badge: { backgroundColor: '#d1fae5', color: '#047857', padding: 4, borderRadius: 4, fontSize: 8, fontWeight: 'bold', alignSelf: 'flex-start', marginBottom: 8 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', color: '#0f172a', marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#e2e8f0', paddingBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  label: { color: '#64748b', fontSize: 10 },
  value: { fontWeight: 'bold', fontSize: 10, fontFamily: 'Courier-Bold' },
  priceBox: { backgroundColor: '#ecfdf5', borderWidth: 2, borderColor: '#10b981', borderRadius: 8, padding: 16, marginVertical: 12 },
  priceLabel: { fontSize: 9, color: '#047857', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 1 },
  priceValue: { fontSize: 26, fontWeight: 'bold', color: '#047857', fontFamily: 'Courier-Bold' },
  watermark: { position: 'absolute', bottom: 30, left: 0, right: 0, textAlign: 'center', fontSize: 8, color: '#94a3b8', fontStyle: 'italic' },
  footer: { position: 'absolute', bottom: 15, left: 40, right: 40, textAlign: 'center', fontSize: 7, color: '#cbd5e1', borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 8 },
})

function fmt(v) {
  if (v === null || v === undefined || v === '') return '-'
  if (typeof v === 'number') return Math.round(v * 100) / 100
  return String(v)
}

function cleanLabel(k) {
  if (k.startsWith('_')) return null
  return k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

function CalculationDoc({ title, type, countrySlug, inputs, results, watermark }) {
  const today = new Date().toLocaleDateString('en-AU', { day: '2-digit', month: 'long', year: 'numeric' })
  const ref = 'TG-CALC-' + Date.now().toString(36).toUpperCase().slice(-8)
  const inputKeys = Object.keys(inputs || {}).filter(k => cleanLabel(k))
  const resultKeys = Object.keys(results || {}).filter(k => cleanLabel(k))

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brand}>timegovern</Text>
            <Text style={styles.subtitle}>Calculation Report - {today}</Text>
          </View>
          <Text style={styles.subtitle}>Ref: {ref}</Text>
        </View>

        <Text style={styles.badge}>{String(type || 'CALCULATION').toUpperCase()}</Text>
        <Text style={{ fontSize: 18, fontWeight: 'bold', marginBottom: 4 }}>{title}</Text>
        {countrySlug && <Text style={{ fontSize: 10, color: '#64748b', marginBottom: 16 }}>Region: {countrySlug}</Text>}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Inputs</Text>
          {inputKeys.length === 0 ? (
            <Text style={{ fontSize: 9, color: '#94a3b8' }}>No input data</Text>
          ) : inputKeys.map((k, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.label}>{cleanLabel(k)}</Text>
              <Text style={styles.value}>{fmt(inputs[k])}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Results</Text>
          {resultKeys.length === 0 ? (
            <Text style={{ fontSize: 9, color: '#94a3b8' }}>No result data</Text>
          ) : resultKeys.map((k, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.label}>{cleanLabel(k)}</Text>
              <Text style={styles.value}>{fmt(results[k])}</Text>
            </View>
          ))}
        </View>

        {resultKeys[0] && (
          <View style={styles.priceBox}>
            <Text style={styles.priceLabel}>Primary Result</Text>
            <Text style={styles.priceValue}>{fmt(results[resultKeys[0]])}</Text>
          </View>
        )}

        <Text style={{ fontSize: 8, color: '#94a3b8', marginTop: 12, fontStyle: 'italic' }}>
          This report is an estimate generated by timegovern.com. Confirm all figures with your lender or financial advisor before making decisions.
        </Text>

        {watermark && (
          <Text style={styles.watermark}>Powered by timegovern.com - Upgrade to Pro to remove this watermark</Text>
        )}

        <Text style={styles.footer}>
          timegovern.com - Time, calculators, and worldwide tools
        </Text>
      </Page>
    </Document>
  )
}

export async function downloadCalculationPdf({ title, type, countrySlug, inputs, results, watermark }) {
  const blob = await pdf(
    <CalculationDoc
      title={title}
      type={type}
      countrySlug={countrySlug}
      inputs={inputs}
      results={results}
      watermark={watermark}
    />
  ).toBlob()
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'timegovern-' + (type || 'calculation') + '-' + Date.now() + '.pdf'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export default CalculationDoc